
ultimate_cron.job.*:
  type: config_entity
  label: 'Cron Job'
  mapping:
    title:
      type: label
      label: 'Title'
    id:
      type: string
      label: 'Machine-readable name'
    module:
      type: string
      label: 'Module Name'
    callback:
      type: string
      label: 'Callback'
    scheduler:
      type: mapping
      label: 'Scheduler'
      mapping:
        id:
          type: string
          label: 'Scheduler'
        configuration:
          type: mapping
          label: 'Scheduler configuration'
    launcher:
      type: mapping
      label: 'Scheduler'
      mapping:
        id:
          type: string
          label: 'Launcher'
        configuration:
          type: mapping
          label: 'Scheduler configuration'
    logger:
      type: mapping
      label: 'Scheduler'
      mapping:
        id:
          type: string
          label: 'Logger'
        configuration:
          type: mapping
          label: 'Scheduler configuration'
