
ultimate_cron.settings:
  type: config_entity
  label: 'Ultimate cron settings'
  mapping:
    bypass_transactional_safe_connection:
      type: boolean
      label: Bypass transactional connection

# @todo make schema pluggable
ultimate_cron.job.*:
  type: config_entity
  label: 'Cron Job'
  mapping:
    title:
      type: label
      label: 'Title'
    id:
      type: string
      label: 'Machine-readable name'
    module:
      type: string
      label: 'Module Name'
    callback:
      type: string
      label: 'Callback'
    scheduler:
      type: mapping
      label: 'Scheduler'
      mapping:
        id:
          type: string
          label: 'Scheduler'
        configuration:
          type: mapping
          label: 'Scheduler configuration'
          mapping:
            rules:
              type: sequence
              label: Scheduler rules
              sequence:
                - type: string
                  label: Scheduling rule
            catch_up:
              type: integer
              label: 'Timeout (s) after job run'
    launcher:
      type: mapping
      label: 'Scheduler'
      mapping:
        id:
          type: string
          label: 'Launcher'
        configuration:
          type: mapping
          label: 'Scheduler configuration'
          mapping:
            timeouts:
              type: mapping
              label: Timeout settings
              mapping:
                lock_timeout:
                  type: integer
                  label: Lock timeout
                max_execution_time:
                  type: integer
                  label: Max execution time
            launcher:
              type: mapping
              label: Launcher settings
              mapping:
                max_threads:
                  type: integer
                  label: Max threads
                poorman_keepalive:
                  type: boolean
                  label: Keepalive
    logger:
      type: mapping
      label: 'Scheduler'
      mapping:
        id:
          type: string
          label: 'Logger'
        configuration:
          type: mapping
          label: 'Scheduler configuration'
          mapping:
            method:
              type: string
              label: Method
            expire:
              type: integer
              label: Expiration
            retain:
              type: integer
              label: Retain X amount of logs
